---

- name: Creates static site vhost
  become: yes
  template:
    src: nginx/static_site.j2
    dest: "/etc/nginx/sites-available/{{ web_olympus_app.name }}_static"
  notify:
    - reload nginx

- name: Enables static site vhost
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ web_olympus_app.name }}_static"
    dest: "/etc/nginx/sites-enabled/{{ web_olympus_app.name }}_static"
    state: link
    force: yes
  notify:
    - reload nginx

- name: Ensures nginx is running
  become: yes
  service:
    name: nginx
    state: started

- name: Gather EC2 facts
  action: ec2_facts

- name: Create AWS Cloudwatch Agent config file
  become: yes
  template:
    src: aws/cloudwatch/cwlogs.cfg.j2
    dest: "/opt/aws/cloudwatch/cwlogs.cfg"
  when: web_olympus_app.aws.cloudwatch.agent.enabled == true

- name: Install AWS Cloudwatch agent
  become: yes
  command: "/opt/aws/cloudwatch/awslogs-agent-setup.py -n -r {{ region }} -c /opt/aws/cloudwatch/cwlogs.cfg"
  when: web_olympus_app.aws.cloudwatch.agent.enabled == true
