---

- name: Ensure Nginx CGI Param Files
  become: yes
  template:
    src: nginx/{{ item }}.j2
    dest: /etc/nginx/includes/{{ web_olympus_app.name }}_{{ item }}
  with_items:
    - fastcgi_params
  notify:
    - reload nginx

- name: Creates site
  become: yes
  template:
    src: nginx/site.j2
    dest: "/etc/nginx/sites-available/{{ web_olympus_app.name }}"
  notify:
    - reload nginx

- name: Enables site
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ web_olympus_app.name }}"
    dest: "/etc/nginx/sites-enabled/{{ web_olympus_app.name }}"
    state: link
    force: yes
  notify:
    - reload nginx
